server:
  port: 8082

spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/kahoot_quiz
    username: root
    password: root
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    database-platform: org.hibernate.dialect.PostgreSQLDialect

jwt:
  secret: u1iV2PwrN+8MfS5K2V7jGfI5PxqMu5LMxdLBewm06x8=
